"""TG-263 dictionary round-trip tests.

Loads the bundled ``synonyms.json`` and asserts that the bridges we care
about (manual ↔ autocontour) resolve to a single TG-263 canonical, and
that the pitfalls (laterality, semantic-distinct overlapping names) do
NOT collapse.

The dictionary is generated by ``scripts/build_synonyms.py`` from the
official TG-263 worksheet. If this test file fails, either the generator
changed its expansion rules or someone hand-edited ``synonyms.json``
breaking a documented behaviour — either way, an audit is needed before
merging.
"""

from __future__ import annotations

from collections import Counter
from importlib.resources import files

import pytest

from autoseg_evaluator.core.matching import similarity
from autoseg_evaluator.data.synonyms import flatten_synonyms, load_synonyms


@pytest.fixture(scope="module")
def synonyms_flat():
    """Load the bundled TG-263 dictionary, flattened for the matcher."""
    res = files("autoseg_evaluator.resources").joinpath("synonyms.json")
    raw = load_synonyms(str(res))
    return flatten_synonyms(raw)


def _assert_tg263(synonyms_flat, a: str, b: str) -> None:
    """Both names must resolve to the same TG-263 canonical (score 1.0, method tg263)."""
    m = similarity(a, b, synonyms_flat=synonyms_flat)
    assert m.score == 1.0, f"Expected {a!r} ↔ {b!r} to score 1.0, got {m.score:.3f}"
    assert m.method == "tg263", (
        f"Expected {a!r} ↔ {b!r} to be TG-263 grounded, got method={m.method!r}"
    )


def _assert_not_collapsed(synonyms_flat, a: str, b: str, *, score_under: float = 1.0) -> None:
    """Two names must not be treated as identical (laterality / semantic distinctness)."""
    m = similarity(a, b, synonyms_flat=synonyms_flat)
    assert m.score < score_under, f"Expected {a!r} ↔ {b!r} to NOT collapse — got {m.score:.3f}"


# ---- Dictionary smoke-tests ---------------------------------------------


def test_dictionary_loaded_with_expected_scale(synonyms_flat):
    """The dictionary should ship with the TG-263 derived ~600 canonicals."""
    canonicals = set(synonyms_flat.values())
    # Loose floor — protects against accidentally shipping the 17-entry starter.
    assert len(canonicals) > 500, (
        f"Expected ≥500 TG-263 canonicals, found {len(canonicals)}. "
        "Did the dictionary regress to the starter file?"
    )


# ---- Laterality bridging -------------------------------------------------


@pytest.mark.parametrize(
    "vendor_name, canonical",
    [
        # Word-order variants and abbreviations clinicians actually use
        ("Parotid_L", "Parotid_L"),
        ("L_Parotid", "Parotid_L"),
        ("LT_Parotid", "Parotid_L"),
        ("Left_Parotid", "Parotid_L"),
        ("Parotid_LT", "Parotid_L"),
        ("Parotid_Left", "Parotid_L"),
        ("LeftParotid", "Parotid_L"),
        ("ParotidLeft", "Parotid_L"),
        # Right side
        ("Parotid_R", "Parotid_R"),
        ("R_Parotid", "Parotid_R"),
        ("Right_Parotid", "Parotid_R"),
        # Spinal cord — separator and casing variants
        ("Spinal_Cord", "SpinalCord"),
        ("Spinal Cord", "SpinalCord"),
        ("SPINALCORD", "SpinalCord"),
        # Optic chiasm — natural-language form
        ("Optic Chiasm", "OpticChiasm"),
        ("Optic_Chiasm", "OpticChiasm"),
        # Brain stem — separator variant
        ("Brain Stem", "Brainstem"),
        ("Brain_Stem", "Brainstem"),
    ],
)
def test_known_vendor_variants_bridge_to_canonical(synonyms_flat, vendor_name, canonical):
    _assert_tg263(synonyms_flat, vendor_name, canonical)


# ---- Description-derived bridges ----------------------------------------


@pytest.mark.parametrize(
    "vendor_name, canonical",
    [
        # Eyeball ↔ Eye (from TG-263 description "Eyeball Left/Right")
        ("Eyeball_L", "Eye_L"),
        ("Eyeball_R", "Eye_R"),
        # OpticNerve ↔ OpticNrv (from description "Optic nerve" + sibling lateralisation)
        ("OpticNerve_L", "OpticNrv_L"),
        ("OpticNerve_R", "OpticNrv_R"),
        ("Optic_Nerve_L", "OpticNrv_L"),
        ("Optic Nerve Left", "OpticNrv_L"),
        # Gland-suffix forms via description
        ("Pituitary_Gland", "Pituitary"),
        ("Thyroid_Gland", "Glnd_Thyroid"),
        # Other descriptive bridges
        ("Bronchial_Tree", "Bronchus"),
        ("Supraglottic Larynx", "Larynx_SG"),
        ("Aorta", "A_Aorta"),
    ],
)
def test_description_derived_bridges(synonyms_flat, vendor_name, canonical):
    _assert_tg263(synonyms_flat, vendor_name, canonical)


# ---- Category-prefix collapse -------------------------------------------


@pytest.mark.parametrize(
    "vendor_name, canonical",
    [
        # "Mandible" alone collapses to Bone_Mandible (no other canonical claims it)
        ("Mandible", "Bone_Mandible"),
    ],
)
def test_category_prefix_collapse(synonyms_flat, vendor_name, canonical):
    _assert_tg263(synonyms_flat, vendor_name, canonical)


# ---- Pitfalls: must NOT collapse ----------------------------------------


@pytest.mark.parametrize(
    "left, right",
    [
        # Laterality must always be preserved
        ("Parotid_L", "Parotid_R"),
        ("Eye_L", "Eye_R"),
        ("Lung_L", "Lung_R"),
        ("Kidney_L", "Kidney_R"),
        ("BrachialPlex_L", "BrachialPlex_R"),
        ("Cochlea_L", "Cochlea_R"),
        ("OpticNrv_L", "OpticNrv_R"),
        # Distinct organs with similar names
        ("Bone_Lacrimal", "Glnd_Lacrimal"),
        ("Cartlg_Thyroid", "Glnd_Thyroid"),
        ("Bone_Frontal", "Lobe_Frontal"),
        ("Bone_Frontal", "Sinus_Frontal"),
        ("Lobe_Frontal", "Sinus_Frontal"),
        # VB_L (Lumbar Vertebra) is NOT the same as a hypothetical "left vertebra"
        # — the generator's pair-detector should have prevented this collapse.
        ("VB_L", "VB_C"),
    ],
)
def test_distinct_canonicals_do_not_collapse(synonyms_flat, left, right):
    _assert_not_collapsed(synonyms_flat, left, right)


# ---- Cross-vendor bridging (the core use case) --------------------------


def test_cross_vendor_bridging_for_optic_nerve(synonyms_flat):
    """Every spelling we've seen in real data should resolve to the same OpticNrv."""
    variants = [
        "OpticNrv_L",  # TG-263 primary
        "OpticNerve_L",  # vendor (Eclipse-style)
        "Optic_Nerve_L",  # vendor (snake case full word)
        "Optic Nerve Left",  # vendor (verbose)
        "L_OpticNrv",  # reverse-order
        "Left_OpticNrv",  # reverse + verbose
        "LeftOpticNrv",  # squished
    ]
    # Every pairwise comparison must be a TG-263 grounded 1.0
    for a in variants:
        for b in variants:
            _assert_tg263(synonyms_flat, a, b)


def test_cross_vendor_bridging_for_parotid(synonyms_flat):
    variants = [
        "Parotid_L",
        "L_Parotid",
        "LT_Parotid",
        "Left Parotid",
        "ParotidLeft",
        "LeftParotid",
    ]
    for a in variants:
        for b in variants:
            _assert_tg263(synonyms_flat, a, b)


# ---- Regression tests for the dictionary-substitution distortion bug ----
#
# v2 originally substituted the TG-263 canonical into the fuzzy comparison.
# When only one side resolved via the dictionary, this produced:
#   • short canonical vs verbose unresolved name → unfair length mismatch
#   • case-preserved canonical vs lowercase fallback → broken cosine overlap
# The fix uses the cleaned-but-not-substituted raw forms for fuzzy. These
# tests pin the v1-like behaviour back in place against the four real-world
# regressions reported on the SAMPLE DATA cohort.


def _best_of(synonyms_flat, gt: str, candidates: list[str]) -> str:
    """Return the candidate that scores highest against ``gt``."""
    scored = [(c, similarity(gt, c, synonyms_flat=synonyms_flat).score) for c in candidates]
    scored.sort(key=lambda x: x[1], reverse=True)
    return scored[0][0]


def test_regression_eye_l_picks_eye_globe_over_kidney(synonyms_flat):
    """Eye_L vs candidates including the description-resolved 'Kidney Left'
    and the unresolved 'Eye Globe Left'. The verbose-but-relevant candidate
    must win over the unrelated short canonical."""
    chosen = _best_of(synonyms_flat, "Eye_L", ["Eye Globe Left", "Kidney Left"])
    assert chosen == "Eye Globe Left"


def test_regression_lens_l_picks_lens_eye_over_lung(synonyms_flat):
    """lens_L vs Lung_L (short, character-similar canonical) and Lens_Eye_L
    (unresolved verbose). The semantically-correct Lens_Eye_L must win."""
    chosen = _best_of(synonyms_flat, "lens_L", ["Lens_Eye_L", "Lung_L"])
    assert chosen == "Lens_Eye_L"


def test_regression_eye_r_picks_matching_side_experimental(synonyms_flat):
    """eye_R vs eye_l_experimental and eye_r_experimental. With consistent
    case handling, the R-matching candidate wins via the single-char cosine
    advantage. Previously the canonical's uppercase R didn't match the
    lowercase r in the candidates."""
    chosen = _best_of(synonyms_flat, "eye_R", ["eye_l_experimental", "eye_r_experimental"])
    assert chosen == "eye_r_experimental"


def test_regression_submang_l_picks_glnd_submand(synonyms_flat):
    """SubmanG_L (typo, doesn't resolve) vs Glnd_Submand_L (resolves) and
    Buccal_Mucosa_L (unresolved). The semantically-closer Glnd_Submand_L
    must win — previously the case mismatch from preserving canonical
    casing handicapped it."""
    chosen = _best_of(synonyms_flat, "SubmanG_L", ["Glnd_Submand_L", "Buccal_Mucosa_L"])
    assert chosen == "Glnd_Submand_L"


# ---- Method labelling ----------------------------------------------------


def test_unresolved_names_fall_back_to_fuzzy(synonyms_flat):
    """Names not in the dictionary still match each other — via fuzzy."""
    m = similarity("CustomROIName", "CustomROIName", synonyms_flat=synonyms_flat)
    assert m.score == 1.0
    assert m.method == "fuzzy"  # literal equality, not dictionary-backed


def test_partial_match_method_is_fuzzy(synonyms_flat):
    """High-similarity but not dictionary-grounded → fuzzy."""
    m = similarity("MyOrgan_LeftSide", "MyOrgan_Left", synonyms_flat=synonyms_flat)
    assert m.method == "fuzzy"
    assert m.score < 1.0


# ---- A canonical name is never another entry's synonym --------------------


def test_a_canonical_name_always_resolves_to_itself():
    """A canonical listed inside another entry's variants must not be captured.

    The shipped dictionary does this eleven times. Two invert laterality:
    Femur_Neck_L lists "Femur Neck_R" as a variant and vice versa, so a
    single-pass flatten leaves Femur_Neck_R resolving to the *left* femoral
    neck — and since organ grouping reads the side off the canonical, right
    contours would be filed under the left organ.
    """
    flat = flatten_synonyms(
        {
            "Bowel_Small": ["Small_Bowel"],
            "Spc_Bowel_Small": ["Bowel_Small"],
            "Femur_Neck_L": ["Femur Neck_R"],
            "Femur_Neck_R": ["Femur Neck_L"],
        }
    )
    assert flat["bowelsmall"] == "Bowel_Small"
    assert flat["femurneckl"] == "Femur_Neck_L"
    assert flat["femurneckr"] == "Femur_Neck_R"


def test_variants_still_resolve_to_their_canonical():
    flat = flatten_synonyms({"Bowel_Small": ["Small_Bowel", "Small"]})
    assert flat["smallbowel"] == "Bowel_Small"
    assert flat["small"] == "Bowel_Small"


def _norm(name: str) -> str:
    return name.lower().replace(" ", "").replace("_", "").replace("-", "")


def test_no_shipped_canonical_is_hijacked():
    """Guards the real dictionary, not just the principle.

    Canonicals that collide with *each other* after normalisation are excluded:
    ``VB_S`` and ``VBs`` are two separate TG-263 entries that both reduce to
    ``vbs``, so the lookup can only hold one of them. That is an ambiguity in
    the standard's naming as this dictionary encodes it, not something the
    flattener can resolve — see :func:`test_colliding_canonicals_are_known`.
    """
    raw = load_synonyms(str(files("autoseg_evaluator.resources").joinpath("synonyms.json")))
    flat = flatten_synonyms(raw)
    seen = Counter(_norm(c) for c in raw if _norm(c))
    for canonical in raw:
        key = _norm(canonical)
        if key and seen[key] == 1:
            assert flat[key] == canonical, f"{canonical} resolves to {flat[key]}"


def test_colliding_canonicals_are_known():
    """Two canonicals reducing to one lookup key is worth noticing, not ignoring.

    Pinned so a future dictionary edit that introduces more collisions fails
    here rather than silently making one of the pair unreachable.
    """
    raw = load_synonyms(str(files("autoseg_evaluator.resources").joinpath("synonyms.json")))
    seen = Counter(_norm(c) for c in raw if _norm(c))
    colliding = sorted(k for k, n in seen.items() if n > 1)
    assert colliding == ["vbs"], f"unexpected canonical collisions: {colliding}"


def test_laterality_inverted_variants_are_refiled():
    """A variant naming the opposite side belongs to the opposite canonical.

    The shipped dictionary once swapped the left and right variant lists for
    two organs, from TG-263's own descriptions; it is now corrected at build,
    but a dictionary edited by hand can make the same error. Read literally,
    "Left_Femur Neck" resolves to the *right* femoral neck.
    """
    flat = flatten_synonyms(
        {
            "Femur_Neck_L": ["Right_Femur Neck", "Femur Neck_Rt"],
            "Femur_Neck_R": ["Left_Femur Neck", "Femur Neck_Lt"],
        }
    )
    assert flat["rightfemurneck"] == "Femur_Neck_R"
    assert flat["femurneckrt"] == "Femur_Neck_R"
    assert flat["leftfemurneck"] == "Femur_Neck_L"
    assert flat["femurnecklt"] == "Femur_Neck_L"


def test_an_inverted_variant_with_no_sibling_is_dropped():
    """Mis-filing a side is worse than losing a synonym."""
    flat = flatten_synonyms({"Femur_Neck_L": ["Right_Femur Neck"]})
    assert "rightfemurneck" not in flat


def test_shipped_dictionary_has_no_surviving_laterality_inversion():
    """Guards the real data, not only the rule: none may survive flattening."""
    from autoseg_evaluator.core.organ_groups import extract_laterality

    raw = load_synonyms(str(files("autoseg_evaluator.resources").joinpath("synonyms.json")))
    flat = flatten_synonyms(raw)
    for variant_key, canonical in flat.items():
        c_side = extract_laterality(canonical)[1]
        v_side = extract_laterality(variant_key)[1]
        if c_side and v_side:
            assert c_side == v_side, f"{variant_key!r} resolves to {canonical!r}"


def test_the_two_known_inverted_organs_resolve_correctly():
    """End to end on the real dictionary, for the organs actually affected."""
    raw = load_synonyms(str(files("autoseg_evaluator.resources").joinpath("synonyms.json")))
    flat = flatten_synonyms(raw)
    cases = {
        "Right_Femur Neck": "Femur_Neck_R",
        "Left_Femur Neck": "Femur_Neck_L",
        "Rt_Common iliac vein": "V_Iliac_R",
        "Lt_Common iliac vein": "V_Iliac_L",
    }
    for spelling, expected in cases.items():
        key = spelling.lower().replace(" ", "").replace("_", "").replace("-", "")
        assert flat[key] == expected, f"{spelling} -> {flat[key]}"


# ---- The TG-263 worksheet's own laterality errors, corrected at build ---------


def _shipped_raw() -> dict:
    import json

    path = files("autoseg_evaluator.resources").joinpath("synonyms.json")
    return json.loads(path.read_text(encoding="utf-8"))


def test_every_shipped_variant_is_listed_under_its_own_side():
    """Corrected at the source, not only re-filed on load.

    The worksheet describes 13 structures as the opposite side to their own
    names; built from those descriptions, the femoral necks and common iliac
    veins listed every right-sided spelling under the left structure.
    """
    from autoseg_evaluator.core.organ_groups import extract_laterality

    raw = load_synonyms(str(files("autoseg_evaluator.resources").joinpath("synonyms.json")))
    for canonical, variants in raw.items():
        side = extract_laterality(canonical)[1]
        for variant in variants:
            other = extract_laterality(variant)[1]
            assert not (side and other and side != other), f"{variant!r} under {canonical!r}"


def test_the_dictionary_says_which_worksheet_descriptions_were_overridden():
    corrections = _shipped_raw()["_tg263_corrections"]
    assert "overridden" in corrections[0]
    named = {line.split(":")[0] for line in corrections[1:]}
    assert named == {
        "Femur_Neck_L",
        "Femur_Neck_R",
        "LN_Ax_Central_R",
        "LN_Neck_II_R",
        "Lobe_Frontal_R",
        "Musc_Sclmast_R",
        "Proc_Condyloid_L",
        "Proc_Condyloid_R",
        "Spc_Retrosty_R",
        "V_Iliac_L",
        "V_Iliac_R",
        "V_Jugular_Int_L",
        "V_Jugular_Int_R",
    }
    # Documentation, never data.
    raw = load_synonyms(str(files("autoseg_evaluator.resources").joinpath("synonyms.json")))
    assert "_tg263_corrections" not in raw


def _generator():
    import importlib.util
    from pathlib import Path

    path = Path(__file__).resolve().parents[1] / "scripts" / "build_synonyms.py"
    spec = importlib.util.spec_from_file_location("build_synonyms", path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def _row(module, primary: str, description: str):
    return module.CSVRow(
        {
            "Target Type": "Anatomic",
            "TG263-Primary Name": primary,
            "TG-263-Reverse Order Name": "",
            "Description": description,
        }
    )


def test_the_generator_overrides_a_known_worksheet_error():
    from collections import defaultdict

    module = _generator()
    row = _row(module, "Femur_Neck_L", "Femur Neck Right")
    conflicts = defaultdict(list)
    module.correct_descriptions([row], conflicts)
    assert row.description == "Femur Neck Left"
    assert "overridden" in conflicts["description_side_corrected"][0]


def test_the_generator_leaves_a_changed_worksheet_row_alone_and_says_so():
    """A later worksheet that fixed or reworded the row is not overwritten."""
    from collections import defaultdict

    module = _generator()
    row = _row(module, "Femur_Neck_L", "Neck of left femur")
    conflicts = defaultdict(list)
    module.correct_descriptions([row], conflicts)
    assert row.description == "Neck of left femur"
    assert conflicts["description_side_correction_not_applied"]


def test_the_generator_reports_an_error_it_has_no_correction_for():
    from collections import defaultdict

    module = _generator()
    row = _row(module, "Kidney_L", "Kidney Right")
    conflicts = defaultdict(list)
    module.correct_descriptions([row], conflicts)
    assert row.description == "Kidney Right"
    assert "Kidney_L" in conflicts["description_side_uncorrected"][0]


def test_every_shipped_variant_resolves_to_the_name_it_is_listed_under():
    """No spelling is claimed by two entries, nor by the wrong side.

    TG-263 lists both Elbow_L and Joint_Elbow_L; prefix-dropping once gave
    Joint_Elbow_L the elbow's spellings too, so "Elbow_L" resolved to Elbow_L
    and "Elbow Left" to Joint_Elbow_L.
    """
    raw = load_synonyms(str(files("autoseg_evaluator.resources").joinpath("synonyms.json")))
    flat = flatten_synonyms(raw)
    for canonical, variants in raw.items():
        for variant in variants:
            assert flat[_norm(variant)] == canonical, f"{variant!r}: {flat[_norm(variant)]}"


def test_elbow_spellings_resolve_to_one_structure(synonyms_flat):
    for spelling in ("Elbow_L", "Elbow Left", "Elbow LT", "Left Elbow", "ElbowL"):
        assert synonyms_flat[_norm(spelling)] == "Elbow_L", spelling
    for spelling in ("Joint_Elbow_L", "L_Elbow_Joint"):
        assert synonyms_flat[_norm(spelling)] == "Joint_Elbow_L", spelling
    assert synonyms_flat[_norm("Bowel")] == "Bowel"


def test_small_and_large_alone_name_no_structure(synonyms_flat):
    """Stripping "Bowel_" left bare adjectives; the bowel spellings remain."""
    assert "small" not in synonyms_flat
    assert "large" not in synonyms_flat
    assert synonyms_flat[_norm("Small Bowel")] == "Bowel_Small"
    assert synonyms_flat[_norm("Large_Bowel")] == "Bowel_Large"


def test_shortened_names_that_name_nothing_are_not_offered(synonyms_flat):
    """Dropping a prefix must not leave a letter, a numeral or a qualifier."""
    for spelling in (
        "R",
        "C",
        "VII",
        "VII_L",
        "Right VII",
        "LV",
        "Base",
        "Base_R",
        "Common",
        "TM_L",
    ):
        assert _norm(spelling) not in synonyms_flat, spelling
    assert synonyms_flat[_norm("CN_VII_L")] == "CN_VII_L"
    assert synonyms_flat[_norm("Tongue_Base")] == "Tongue_Base"
    # Vertebra codes are how vertebrae are named, so they stay.
    assert synonyms_flat[_norm("C1")] == "VB_C1"
    assert synonyms_flat[_norm("T12")] == "VB_T12"
