"""TG-263 dictionary round-trip tests.

Loads the bundled ``synonyms.json`` and asserts that the bridges we care
about (manual ↔ autocontour) resolve to a single TG-263 canonical, and
that the pitfalls (laterality, semantic-distinct overlapping names) do
NOT collapse.

The dictionary is generated by ``scripts/build_synonyms.py`` from the
official TG-263 worksheet. If this test file fails, either the generator
changed its expansion rules or someone hand-edited ``synonyms.json``
breaking a documented behaviour — either way, an audit is needed before
merging.
"""

from __future__ import annotations

from importlib.resources import files

import pytest

from autoseg_evaluator.core.matching import similarity
from autoseg_evaluator.data.synonyms import flatten_synonyms, load_synonyms


@pytest.fixture(scope="module")
def synonyms_flat():
    """Load the bundled TG-263 dictionary, flattened for the matcher."""
    res = files("autoseg_evaluator.resources").joinpath("synonyms.json")
    raw = load_synonyms(str(res))
    return flatten_synonyms(raw)


def _assert_tg263(synonyms_flat, a: str, b: str) -> None:
    """Both names must resolve to the same TG-263 canonical (score 1.0, method tg263)."""
    m = similarity(a, b, synonyms_flat=synonyms_flat)
    assert m.score == 1.0, f"Expected {a!r} ↔ {b!r} to score 1.0, got {m.score:.3f}"
    assert m.method == "tg263", (
        f"Expected {a!r} ↔ {b!r} to be TG-263 grounded, got method={m.method!r}"
    )


def _assert_not_collapsed(synonyms_flat, a: str, b: str, *, score_under: float = 1.0) -> None:
    """Two names must not be treated as identical (laterality / semantic distinctness)."""
    m = similarity(a, b, synonyms_flat=synonyms_flat)
    assert m.score < score_under, (
        f"Expected {a!r} ↔ {b!r} to NOT collapse — got {m.score:.3f}"
    )


# ---- Dictionary smoke-tests ---------------------------------------------


def test_dictionary_loaded_with_expected_scale(synonyms_flat):
    """The dictionary should ship with the TG-263 derived ~600 canonicals."""
    canonicals = set(synonyms_flat.values())
    # Loose floor — protects against accidentally shipping the 17-entry starter.
    assert len(canonicals) > 500, (
        f"Expected ≥500 TG-263 canonicals, found {len(canonicals)}. "
        "Did the dictionary regress to the starter file?"
    )


# ---- Laterality bridging -------------------------------------------------


@pytest.mark.parametrize(
    "vendor_name, canonical",
    [
        # Word-order variants and abbreviations clinicians actually use
        ("Parotid_L", "Parotid_L"),
        ("L_Parotid", "Parotid_L"),
        ("LT_Parotid", "Parotid_L"),
        ("Left_Parotid", "Parotid_L"),
        ("Parotid_LT", "Parotid_L"),
        ("Parotid_Left", "Parotid_L"),
        ("LeftParotid", "Parotid_L"),
        ("ParotidLeft", "Parotid_L"),
        # Right side
        ("Parotid_R", "Parotid_R"),
        ("R_Parotid", "Parotid_R"),
        ("Right_Parotid", "Parotid_R"),
        # Spinal cord — separator and casing variants
        ("Spinal_Cord", "SpinalCord"),
        ("Spinal Cord", "SpinalCord"),
        ("SPINALCORD", "SpinalCord"),
        # Optic chiasm — natural-language form
        ("Optic Chiasm", "OpticChiasm"),
        ("Optic_Chiasm", "OpticChiasm"),
        # Brain stem — separator variant
        ("Brain Stem", "Brainstem"),
        ("Brain_Stem", "Brainstem"),
    ],
)
def test_known_vendor_variants_bridge_to_canonical(synonyms_flat, vendor_name, canonical):
    _assert_tg263(synonyms_flat, vendor_name, canonical)


# ---- Description-derived bridges ----------------------------------------


@pytest.mark.parametrize(
    "vendor_name, canonical",
    [
        # Eyeball ↔ Eye (from TG-263 description "Eyeball Left/Right")
        ("Eyeball_L", "Eye_L"),
        ("Eyeball_R", "Eye_R"),
        # OpticNerve ↔ OpticNrv (from description "Optic nerve" + sibling lateralisation)
        ("OpticNerve_L", "OpticNrv_L"),
        ("OpticNerve_R", "OpticNrv_R"),
        ("Optic_Nerve_L", "OpticNrv_L"),
        ("Optic Nerve Left", "OpticNrv_L"),
        # Gland-suffix forms via description
        ("Pituitary_Gland", "Pituitary"),
        ("Thyroid_Gland", "Glnd_Thyroid"),
        # Other descriptive bridges
        ("Bronchial_Tree", "Bronchus"),
        ("Supraglottic Larynx", "Larynx_SG"),
        ("Aorta", "A_Aorta"),
    ],
)
def test_description_derived_bridges(synonyms_flat, vendor_name, canonical):
    _assert_tg263(synonyms_flat, vendor_name, canonical)


# ---- Category-prefix collapse -------------------------------------------


@pytest.mark.parametrize(
    "vendor_name, canonical",
    [
        # "Mandible" alone collapses to Bone_Mandible (no other canonical claims it)
        ("Mandible", "Bone_Mandible"),
    ],
)
def test_category_prefix_collapse(synonyms_flat, vendor_name, canonical):
    _assert_tg263(synonyms_flat, vendor_name, canonical)


# ---- Pitfalls: must NOT collapse ----------------------------------------


@pytest.mark.parametrize(
    "left, right",
    [
        # Laterality must always be preserved
        ("Parotid_L", "Parotid_R"),
        ("Eye_L", "Eye_R"),
        ("Lung_L", "Lung_R"),
        ("Kidney_L", "Kidney_R"),
        ("BrachialPlex_L", "BrachialPlex_R"),
        ("Cochlea_L", "Cochlea_R"),
        ("OpticNrv_L", "OpticNrv_R"),
        # Distinct organs with similar names
        ("Bone_Lacrimal", "Glnd_Lacrimal"),
        ("Cartlg_Thyroid", "Glnd_Thyroid"),
        ("Bone_Frontal", "Lobe_Frontal"),
        ("Bone_Frontal", "Sinus_Frontal"),
        ("Lobe_Frontal", "Sinus_Frontal"),
        # VB_L (Lumbar Vertebra) is NOT the same as a hypothetical "left vertebra"
        # — the generator's pair-detector should have prevented this collapse.
        ("VB_L", "VB_C"),
    ],
)
def test_distinct_canonicals_do_not_collapse(synonyms_flat, left, right):
    _assert_not_collapsed(synonyms_flat, left, right)


# ---- Cross-vendor bridging (the core use case) --------------------------


def test_cross_vendor_bridging_for_optic_nerve(synonyms_flat):
    """Every spelling we've seen in real data should resolve to the same OpticNrv."""
    variants = [
        "OpticNrv_L",          # TG-263 primary
        "OpticNerve_L",        # vendor (Eclipse-style)
        "Optic_Nerve_L",       # vendor (snake case full word)
        "Optic Nerve Left",    # vendor (verbose)
        "L_OpticNrv",          # reverse-order
        "Left_OpticNrv",       # reverse + verbose
        "LeftOpticNrv",        # squished
    ]
    # Every pairwise comparison must be a TG-263 grounded 1.0
    for a in variants:
        for b in variants:
            _assert_tg263(synonyms_flat, a, b)


def test_cross_vendor_bridging_for_parotid(synonyms_flat):
    variants = [
        "Parotid_L",
        "L_Parotid",
        "LT_Parotid",
        "Left Parotid",
        "ParotidLeft",
        "LeftParotid",
    ]
    for a in variants:
        for b in variants:
            _assert_tg263(synonyms_flat, a, b)


# ---- Regression tests for the dictionary-substitution distortion bug ----
#
# v2 originally substituted the TG-263 canonical into the fuzzy comparison.
# When only one side resolved via the dictionary, this produced:
#   • short canonical vs verbose unresolved name → unfair length mismatch
#   • case-preserved canonical vs lowercase fallback → broken cosine overlap
# The fix uses the cleaned-but-not-substituted raw forms for fuzzy. These
# tests pin the v1-like behaviour back in place against the four real-world
# regressions reported on the SAMPLE DATA cohort.


def _best_of(synonyms_flat, gt: str, candidates: list[str]) -> str:
    """Return the candidate that scores highest against ``gt``."""
    scored = [(c, similarity(gt, c, synonyms_flat=synonyms_flat).score) for c in candidates]
    scored.sort(key=lambda x: x[1], reverse=True)
    return scored[0][0]


def test_regression_eye_l_picks_eye_globe_over_kidney(synonyms_flat):
    """Eye_L vs candidates including the description-resolved 'Kidney Left'
    and the unresolved 'Eye Globe Left'. The verbose-but-relevant candidate
    must win over the unrelated short canonical."""
    chosen = _best_of(synonyms_flat, "Eye_L", ["Eye Globe Left", "Kidney Left"])
    assert chosen == "Eye Globe Left"


def test_regression_lens_l_picks_lens_eye_over_lung(synonyms_flat):
    """lens_L vs Lung_L (short, character-similar canonical) and Lens_Eye_L
    (unresolved verbose). The semantically-correct Lens_Eye_L must win."""
    chosen = _best_of(synonyms_flat, "lens_L", ["Lens_Eye_L", "Lung_L"])
    assert chosen == "Lens_Eye_L"


def test_regression_eye_r_picks_matching_side_experimental(synonyms_flat):
    """eye_R vs eye_l_experimental and eye_r_experimental. With consistent
    case handling, the R-matching candidate wins via the single-char cosine
    advantage. Previously the canonical's uppercase R didn't match the
    lowercase r in the candidates."""
    chosen = _best_of(synonyms_flat, "eye_R", ["eye_l_experimental", "eye_r_experimental"])
    assert chosen == "eye_r_experimental"


def test_regression_submang_l_picks_glnd_submand(synonyms_flat):
    """SubmanG_L (typo, doesn't resolve) vs Glnd_Submand_L (resolves) and
    Buccal_Mucosa_L (unresolved). The semantically-closer Glnd_Submand_L
    must win — previously the case mismatch from preserving canonical
    casing handicapped it."""
    chosen = _best_of(synonyms_flat, "SubmanG_L", ["Glnd_Submand_L", "Buccal_Mucosa_L"])
    assert chosen == "Glnd_Submand_L"


# ---- Method labelling ----------------------------------------------------


def test_unresolved_names_fall_back_to_fuzzy(synonyms_flat):
    """Names not in the dictionary still match each other — via fuzzy."""
    m = similarity("CustomROIName", "CustomROIName", synonyms_flat=synonyms_flat)
    assert m.score == 1.0
    assert m.method == "fuzzy"  # literal equality, not dictionary-backed


def test_partial_match_method_is_fuzzy(synonyms_flat):
    """High-similarity but not dictionary-grounded → fuzzy."""
    m = similarity("MyOrgan_LeftSide", "MyOrgan_Left", synonyms_flat=synonyms_flat)
    assert m.method == "fuzzy"
    assert m.score < 1.0
